### ISSUE TITLE
integration test failed with "Error: API Server health check timed out"

### ISSUE THREAD

**Issue by jessehu** [cloudfoundry-incubator/app-autoscaler#136]
I'm running integration test via "pushd test/integration/api; npm install; npm run integration; popd" on Mac OS 10.12 againt the latest code in develop branch:

npm WARN package.json autoscaler-api-integration@1.0.0 No repository field.
npm WARN package.json autoscaler-api-integration@1.0.0 No license field.

> autoscaler-api-integration@1.0.0 integration /Users/huh/code/cloudfoundry/app-autoscaler/test/integration/api
> cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js

  API Server-Scheduler Integration tests
Starting the Scheduler..................
Scheduler Health check succeeded. Server is up and running !
    1) "before all" hook
Scheduler stopped successfully
API Server stopped successfully

  0 passing (31s)
  1 failing

  1) API Server-Scheduler Integration tests "before all" hook:
     Error: API Server health check timed out
      at Request._callback (api.test.js:47:15)
      at self.callback (node_modules/request/request.js:186:22)
      at Request.onRequestError (node_modules/request/request.js:845:8)
      at Socket.socketErrorListener (_http_client.js:267:9)
      at emitErrorNT (net.js:1253:8)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "integration"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! autoscaler-api-integration@1.0.0 integration: `cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the autoscaler-api-integration@1.0.0 integration script 'cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js'.
npm ERR! This is most likely a problem with the autoscaler-api-integration package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs autoscaler-api-integration
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls autoscaler-api-integration
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/huh/code/cloudfoundry/app-autoscaler/test/integration/api/npm-debug.log

**Comment by jessehu** [comment]
cat /Users/huh/code/cloudfoundry/app-autoscaler/test/integration/api/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'integration' ]
2 info using npm@2.15.5
3 info using node@v4.4.6
4 verbose run-script [ 'preintegration', 'integration', 'postintegration' ]
5 info preintegration autoscaler-api-integration@1.0.0
6 info integration autoscaler-api-integration@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info autoscaler-api-integration@1.0.0 Failed to exec integration script
9 verbose stack Error: autoscaler-api-integration@1.0.0 integration: `cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid autoscaler-api-integration@1.0.0
11 verbose cwd /Users/huh/code/cloudfoundry/app-autoscaler/test/integration/api
12 error Darwin 16.0.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "integration"
14 error node v4.4.6
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error autoscaler-api-integration@1.0.0 integration: `cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js`
17 error Exit status 1
18 error Failed at the autoscaler-api-integration@1.0.0 integration script 'cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js'.
18 error This is most likely a problem with the autoscaler-api-integration package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     cross-env DB_URI=postgres://postgres:postgres@127.0.0.1:5432/autoscaler cross-env SCHEDULER_URI=http://127.0.0.1:8080  cross-env APISERVER_URI=http://127.0.0.1:3002 node_modules/.bin/_mocha --timeout=40000 api.test.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs autoscaler-api-integration
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls autoscaler-api-integration
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by fraenkel** [comment]
This is a known issue and already being tracked.
Instead of fixing the current integration tests we are going to migrate them to Go.
