### ISSUE TITLE
"bin/deploy.sh myenv" failed due to servicebroker.war not found

### ISSUE THREAD

**Issue by jessehu** [cloudfoundry-incubator/app-autoscaler#139]
$ bin/deploy.sh myenv
Updating app AutoScaling in org abc / space abc as abc...
OK

Using route autoscaling.apps.abc.local
FAILED
Error processing app files: lstat /opt/cf/app-autoscaler/server: no such file or directory
Updating app AutoScalingAPI in org abc / space abc as abc...
OK

Using route autoscalingapi.apps.abc.local
FAILED
Error processing app files: lstat /opt/cf/app-autoscaler/api/target: no such file or directory
Updating app AutoScalingServiceBroker in org abc / space abc as abc...
OK

Using route autoscalingservicebroker.apps.abc.local
FAILED
Error processing app files: lstat /opt/cf/app-autoscaler/servicebroker/target: no such file or directory

I found that 'mvn package' doesn't generate servicebroker.war and api.war

$ mvn package -Denv=myenv -DskipTests
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] db
[INFO] app-autoscaler
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building db 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
......
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building app-autoscaler 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] db ................................................. SUCCESS [  0.835 s]
[INFO] app-autoscaler ..................................... SUCCESS [  0.001 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.906 s
[INFO] Finished at: 2016-11-28T16:21:17+08:00
[INFO] Final Memory: 15M/309M
[INFO] ------------------------------------------------------------------------

**Comment by fraenkel** [comment]
Are you using the master branch? Develop is still under development and does not work.

**Comment by jessehu** [comment]
I'm using the development branch (checked out by default). The master branch works. Thanks.
