### ISSUE TITLE
Is it possible to measure response time?

### ISSUE THREAD

**Issue by yy8848** [cloudfoundry-incubator/app-autoscaler#182]
It is possible to measure something like average response time in two minutes? Sometimes customers might want to have SLA like this. And it would be great to auto-scale instances according to the SLA items.

And not sure whether streaming technology can help here. A typical streaming setup might include components like Metric Agent, Kafka, Spark Streaming, InfluxDB and Grafana. Streaming infrastructure can be used to compute aggregation (max, min, median etc.) for the given time window, trigger actions to scale up or down according to rules and save the metrics (or aggregates) to time series database. In the end Grafana can be used to view the graphs.

**Comment by fraenkel** [comment]
The pieces are in place where this could be possible. The missing parts are much like you identified. You need to collect the metrics and have the ability to define this metric with all the necessary wiring to pull the data.

**Comment by yy8848** [comment]
Agree. There should be a solution to wire all the pieces together. 
In my mind, the most challenging part are the triggering rules and how to determine the necessary instances to scale up or down based on statistics. For example how to express conditions like response time of 90% request should be above 200 ms. And if the mean response time is 300 ms with 10 instances, 2 instances will be needed to achieve the target response time, which is forecasted using historical data.
