### ISSUE TITLE
Question: Enable autoscaler via api?

### ISSUE THREAD

**Issue by bobbyhubbard** [cloudfoundry-incubator/app-autoscaler#205]
So we bind new apps to an autoscaler service instance via the manifest. This insures that new versions of the same app get bound to the autoscale service. However, at startup, the autoscaler is not enabled. So its bound, but turned off. We then have to go into the gui, and enable the autoscaler for a specific app. Surely there is a way to do this outside of the gui. We are currently on PCF1.9x. Do we have any options?

**Comment by fraenkel** [comment]
This is not the same service. Please reach out to CF support for your request.
