### ISSUE TITLE
This is not issue, juts a query

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/app-autoscaler#222]
Hi thanks for your opensource, i wounder this opensource has dashboard or it only supports API and allow the developers to build their customized dashboard ?, If available please provide the samples link. Thanks in advance

Regards
Abhilash S

**Comment by boyang9527** [comment]
no, so far we don't have plan a to provide a dashboard.  There will be public APIs and service borker enhancements to enable building your own dashboard.
