### ISSUE TITLE
This is not issue just query

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/app-autoscaler#231]
Is this autoscaler scales only memory or scale cpu & disk
Regards 
Abhilash S

**Comment by boyang9527** [comment]
is your question scaling **based on**  memory/cpu/disk, or scale the CPU/DISK allocation to app ?

**Comment by abhilash07** [comment]
Hi @boyang9527 thanks for your response, i mean is this autoscaler will scale memory/cpu/disk and allocate memorycpu/disk if resources or not enough for application running in a container. For example i am running application it is out of disk or more cpu core it will collect the cpu or disk or memory metrics and detect that cpu or disk or memory is out of resources then it will auto scale and allocate the resources ?????

**Comment by boyang9527** [comment]
Now we only support memory based scaling, i.e. collect memory usage and change the number of application instances based on the user defined policy.  We are working on the support of scaling based on response time and throughput(RPS).

CPU is shared among the containers in the same DEA/CELL, so it is problematic if we scale based on CPU.  We will reconsider this given there is a new feature in Garden that we can set CPU limit for each container. 

Cloud Foundry application usually is not disk IO intensive, so we don't support scaling based on disk usage,  though the implementation is general enough to support any type of metric. Let us know if you have any use cases requesting this feature... so far it is not a priority in backlog.

By the way,  the scaling we talk about here is horizontal scaling. When scaling out, more instances will be added, while the  instances will have the same memory/disk allocation.

**Comment by abhilash07** [comment]
Hi @boyang9527  thanks for your information i agree with your discussion regarding disk scaling. Thank you for considering CPU scaling as a feature.
