### ISSUE TITLE
VCAP Services Credentials Null

### ISSUE THREAD

**Issue by kmj940101** [cloudfoundry-incubator/app-autoscaler#253]
I created an autoscaler service instance and bound my app to it.

When I execute ```cf env < MY APP> ```, I cannot find any the autoscaler service credentials.

```
 "VCAP_SERVICES": {
  "autoscaler": [
   {
    "credentials": null,
    "label": "autoscaler",
    "name": "portal-autoscaler",
    "plan": "autoscaler-free-plan",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [],
    "volume_mounts": []
   }
  ]
```

Here is the link of the API document: 
https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/docs/API_usage.rst#api-endpoint

Any help would be appreciated!

**Comment by boyang9527** [comment]
which one did you deployed? the one on master branch (v1) that is a total Java Impl, or the one in app-autoscaler-release project which is a v2 rewriting?

If it is the latter, the public API is still in development... and it  will use the UAA oauth-token so you don't need credentials in VCAP_SERVICES any more.
