### ISSUE TITLE
How to test API?

### ISSUE THREAD

**Issue by 7CHANHO** [cloudfoundry-incubator/app-autoscaler#257]
## Context
I have deployed 'app-autoscaler-release' on CF(Open Source).
I am currently developing an autoscaler dashboard for users.

## Question
I was test the API in the previous version (master branch) as follows:
```
$ curl -H "Authorization: Bearer [ACCESS-TOKEN]" "[API-APP-URL]/v1/apps/[APP-ID]/policy/"
```
```
{"instanceMinCount":1,"instanceMaxCount":2,"policyTriggers":[{"metricType":"Memory","statWindow":120,"breachDuration":120,"lowerThreshold":1,"lowerThreshold_set":true,"upperThreshold":1,"upperThreshold_set":true,"instanceStepCountDown":1,"instanceStepCountUp":1,"stepDownCoolDownSecs":120,"stepUpCoolDownSecs":120}],"schedules":null,"policyState":"ENABLED"}
```

In the current version, however, this way is not work.
```
curl: (56) Recv failure: Connection reset by peer
```

I am wondering how to test the API.

**Comment by pradyutsarma** [comment]
The api that you mention above is an internal api and not supposed to be consumed outside of the service boundaries.
There will be a different API that will be exposed (as of now under development) to be used by service/platform operators to build their dashboards with.

**Comment by 7CHANHO** [comment]
@pradyutsarma Thank you! Have a good day!
