### ISSUE TITLE
Replace the autoscaler.network.subnet with individual independent addresses

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/app-autoscaler#27]
[Carried over from cfibmers/open-Autoscaler]

We'd like to use this plugin, but its assumption that the four component servers reside on contiguous network addresses on one subnet doesn't fit with our structure.

I understand that the bosh-release is being completely rewritten from the old open-Autoscaler,
and will most likely be in its own app-autoscaler-release repo, but we still have feedback on how to describe a generic network that work for most users. The current bosh-release in open-Autoscaler was too restrictive.

**Comment by boyang9527** [comment]
can you make the changes and PR https://github.com/cfibmers/open-Autoscaler?

**Comment by boyang9527** [comment]
close since it is outdated and we have bosh release for autoscaler
