### ISSUE TITLE
Question about the public API

### ISSUE THREAD

**Issue by kmj940101** [cloudfoundry-incubator/app-autoscaler#271]
Hello!

I am wondering if the public API has been exposed or not.
If it is available, how can I use the public API from my local machine?

```
minjeong@ubuntu:~$ curl https://api_public.bosh-lite.com:6106/v1/apps/9df61bc3-4bdb-484c-b4b8-21a147178fd1/policy --insecure
curl: (7) Failed to connect to api_public.bosh-lite.com port 6106: Connection refused
```

Related Commits 
- https://github.com/cloudfoundry-incubator/app-autoscaler/pull/263 
- https://github.com/cloudfoundry-incubator/app-autoscaler-release/pull/72

Thank you in advance!

**Comment by qibobo** [comment]
@kmj940101 For "api_public" of https://api_public.bosh-lite.com:6106, is it the hostname of your apiserver? Currently the apiserver has no public hostname, and you can access it by its ip address.

**Comment by kmj940101** [comment]
@qibobo Thank you for your reply.
No. It is not the hostname. I thought an end point has been added.
What is this public API about? (Commit: https://github.com/cloudfoundry-incubator/app-autoscaler/pull/263)

**Comment by qibobo** [comment]
@kmj940101 pr#263 is for public api and it still need oauth and some other code to be added before  its opening.
