### ISSUE TITLE
date parsing in server/.../metric/bean/CFInstance.java fails

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/app-autoscaler#31]
Incoming times look like this:
2016-05-25T19:54:45.507700194Z

The date parser specifes this format:
"yyyy-MM-dd HH:mm:ss ZZZZZ"

It should be "yyyy-MM-ddTHH:mm:ss.SSS" and the incoming string gets cut off 
three digits to the right of the ".". There's no need for time-zone data as the
incoming times are in UTC. Don't include more digits in the sub-second part
because parseDigit interprets this as milliseconds, and will overflow.  For example,
the time string "2016-05-25T12:34:56.2000" is equivalent to "2016-05-25T12:34:58.000",
as 2000 msec = 1 sec.

**Comment by fraenkel** [comment]
closing since we have pr #32
