### ISSUE TITLE
apiserver not able to resolve service broker internal address

### ISSUE THREAD

**Issue by Nishanksingla** [cloudfoundry-incubator/app-autoscaler#322]
After the successful deployment, when I try to update policy, I am seeing this error in apiserver logs 

```
source":"autoscaler:apiserver","text":"Error occurred during check binding ","log_level":"error","data":{"appId":"f898e6fd-94f5-4eae-825a-ddbb73cd2a4a","error":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"servicebroker.service.cf.internal","host":"servicebroker.service.cf.internal","port":"6107"}}}
```
I have checked everything but I am not getting why this url `servicebroker.service.cf.internal` not getting resolved to service broker ip address. Please give me some suggestions to resolve this.

**Comment by qibobo** [comment]
@Nishanksingla  Do you use the latest code of app-autoscaler-release (https://github.com/cloudfoundry-incubator/app-autoscaler-release)?

**Comment by Nishanksingla** [comment]
I think so. I cloned the repo on 15th March. Service broker is able to resolve the postgres address and is able to connect to it. I don't understand why can't apiserver resolve servicebroker internal address.
Can you please provide me some updates? 

Will using the latest code resolve this issue?

**Comment by qibobo** [comment]
@Nishanksingla After cloning app-autoscaler-release, did you update the app-autoscaler in app-autoscaler-release? If so, it may cause the problem. So could you just use develop or master branch of app-autoscaler-release without updating its submodule :app-autoscaler to check whether your issue is still there?

**Comment by Nishanksingla** [comment]
Hi @qibobo 

I made it work. What was missing in the initial templates and the template you sent me was consul agent service check for ServiceBroker that's why API server was not able to resolve the servicebroker internal name to its IP. 

Can you please explain the terms of policy API? What does `stat_window_secs`  and `breach_duration_secs` mean? How do they work?

**Comment by boyang9527** [comment]
stat_window_secs is the time interval we aggregate metrics from application instances. Setting this value longer will smooth the metric values, it may reduce impact on potential noisy data points, but this may also cause insensitivity....

breach_duration_secs defines the time period that scaling will be triggered if all the data points during this time period always breach the scaling rule. 

For example,  if you set memory usage threshold to be 70%, breach_duration_secs = 120 means the scaling out will happen when memory usage >= 70% for 120 seconds.

**Comment by boyang9527** [comment]
stat_window_secs is used to control how to aggregate metrics.
stat_window_secs = 300 means the  metric of an app will be the average of the metrics from each application instance in the past 300 seconds.

**Comment by cdlliuy** [comment]
closed for no further updates.
