### ISSUE TITLE
App is only scaling up not scaling down once memory consumption is below the defined policy.

### ISSUE THREAD

**Issue by Nishanksingla** [cloudfoundry-incubator/app-autoscaler#327]
I am testing my autoscaler deployment. I created the service and bounded it with an app. After defining the policy and increase the traffic load, the app is scaling up and it's not scaling down when memory usage of each instance is below the threshold defined in the policy.  
The app is now running with the maximum number of instances defined in the policy.

**Comment by cdlliuy** [comment]
@Nishanksingla , could you provide your policy and the current stats information of the app? 

we may require more information for debugging purpose later.

**Comment by Nishanksingla** [comment]
Hi 

Here is the policy. 

```
{
    "instance_min_count": 1,
    "instance_max_count": 4,
    "scaling_rules": [
        {
            "metric_type": "memoryused",
            "stat_window_secs": 300,
            "breach_duration_secs": 60,
            "threshold": 10,
            "operator": "<",
            "cool_down_secs": 300,
            "adjustment": "-1"
        },
        {
            "metric_type": "memoryused",
            "stat_window_secs": 300,
            "breach_duration_secs": 60,
            "threshold": 20,
            "operator": ">=",
            "cool_down_secs": 300,
            "adjustment": "+1"
        }
    ]
}
```

Here are details of the app instances

 ```
 state     since                  cpu    memory         disk           details
#0   running   2018-04-09T18:15:23Z   0.2%   419M of 1G     135.3M of 1G   
#1   running   2018-04-10T16:12:39Z   0.1%   445.7M of 1G   135.3M of 1G   
#2   running   2018-04-10T15:53:47Z   0.1%   431M of 1G     135.3M of 1G   
#3   running   2018-04-09T20:02:08Z   0.1%   438.2M of 1G   135.3M of 1G   
```

**Comment by boyang9527** [comment]
1. you are using metric "memoryused" which is the absolute value of used memory. And you set the lower threshold to be 10, which means scale down when used memory < 10MB. Apparently all your instances have memory used  more than 10MB

2. you can use metric "memoryutil" which is the percentage of the memory used / memory limt, that is what you intent to use?

**Comment by Nishanksingla** [comment]
Thanks, @boyang9527 for the valuable reply. 
Can you please tell me where I can get information regarding other metric_types? 
Is there a metric type for CPU usage?

**Comment by boyang9527** [comment]
https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/docs/Public_API.rst

**Comment by boyang9527** [comment]
we don't support CPU now... given the CPU is shared among containers in the same cell. Using CPU usage directly will be problematic.  

See more discussions here: https://docs.google.com/document/d/1PBOati9Opusfss2s7HX_Hl3D0A-SRTmmMhNk2NRCUSo/edit

**Comment by boyang9527** [comment]
there is no documentation right now except  the API doc.. will add

**Comment by Nishanksingla** [comment]
Hi @boyang9527 

Thank you for the replies. I appreciate a lot. With `memoryutil` I was able to scale down the application. But the problem with using `memoryutil` metric is that not all the time memory utilization increases with the increase in traffic. I was testing with an application where CPU utilization was increasing with the traffic but the memory utilization was not spiking a lot thus not triggering the rules. 

Pivotal autoscaler uses CPU utilization for the scale up and scale down operation. I understand from the document that you sent that CPU metric exposed by Garden/Diego/Cloud Foundry is worse but still, I believe it's a good number in the sense of giving an idea about the traffic load and taking scaling up decision. 

If you know of other metric type that could be useful please let me know. 

Thanks
Nishank

**Comment by boyang9527** [comment]
I don't think using the CPU utilization reported by CF to scale app is correct.  It does not indicate whether you are running out of CPU resources or not. 

We will not add cpu based unless Garden adds CPU limit or we come up with a new idea to handle the weighted shared cpu strategy in CF. 

You can use responsetime or throughput instead.  To enable this, you need to make sure you are using "streaming" as the method to collect metrics.  The bosh release defaults to "streaming", but just want to make sure you did not change it in your deployment manifest. 

https://github.com/cloudfoundry-incubator/app-autoscaler-release/blob/develop/jobs/metricscollector/spec#L91

**Comment by Nishanksingla** [comment]
Thank you for the response. 
Can I set policy to 2 different metrics? Like this 

```
{
   "instance_min_count":1,
   "instance_max_count":4,
   "scaling_rules":[
      {
         "metric_type":"memoryutil",
         "stat_window_secs":120,
         "breach_duration_secs":60,
         "threshold":40,
         "operator":"<",
         "cool_down_secs":60,
         "adjustment":"-1"
      },
      {
         "metric_type":"memoryutil",
         "stat_window_secs":120,
         "breach_duration_secs":60,
         "threshold":50,
         "operator":">=",
         "cool_down_secs":60,
         "adjustment":"+1"
      },
      {
         "metric_type":"responsetime",
         "stat_window_secs":120,
         "breach_duration_secs":60,
         "threshold":7000,
         "operator":"<",
         "cool_down_secs":60,
         "adjustment":"-1"
      },
      {
         "metric_type":"responsetime",
         "stat_window_secs":120,
         "breach_duration_secs":60,
         "threshold":10000,
         "operator":">=",
         "cool_down_secs":60,
         "adjustment":"+1"
      }
   ]
}
```

**Comment by cdlliuy** [comment]
@Nishanksingla , @rohitsharma04  ,  yes, it is true to set policies against 2 different metric type, but the scaling result depends on your application characteristics. 

For above policy,  if your memoryutil is lower than <40% (i.e. not a memory intensive app), but the response time is longer than 10000 , then  the target instance number may go up and down

**Comment by Nishanksingla** [comment]
Thank you @cdlliuy for the reply and the adding the documents. I would definitely go through them.
