### ISSUE TITLE
Question on Autoscaling .

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry-incubator/app-autoscaler#345]
I configured autoscaling in my dev version of cloudfoundry cf release 256

I have applied the below policy to the application .

scenario:-

My application is having one instance only .
At the start start_date_time my application scales from 1 to 3 successfully .
But at the end_time it doesn't scale back to original count which is 1 

Per sample catalog definition it should scale down .(I have a feeling that i am unable to understand specific_date schedule ) Any advice is great .
                          instance_min_count:
                            type: integer
                            minimum: 1
                            description: The number of instances to scale down to once recurrence period
                          instance_max_count:
                            type: integer
                            minimum: 1
                            description: Maximum number of instances to scale up during recurrence period
                          initial_min_instance_count:
                            type: integer
                            minimum: 1
                            description: The number of instances to scale up to as soon as the recurrence period starts

```{
  "instance_min_count": 1,
  "instance_max_count": 4,
  "schedules": {
    "timezone": "America/New_York",
    "specific_date": [{
      "start_date_time": "2018-05-30T17:45",
      "end_date_time": "2018-05-30T17:50",
      "instance_min_count": 2,
      "instance_max_count": 4,
      "initial_min_instance_count": 3
    }]
  }
}```

**Comment by cdlliuy** [comment]
@nsharmacovs ,  the policy definition can't achieve your expected scenario since you don't have any dynamic scale rule definition.

The min/max instance count defines a range in which the instance number could be.   
The initial_min_instance_count in the specific date schedule defines the instance number must be adjust to that number when the schedule starts.  
Then, if you want to dynamic scale out / in per your runtime metrics, you still need a dynamic scaling rule.

**Comment by nsharmacovs** [comment]
HI thanks for you response. Could you give an example of dynamic scale out / in and how to set it?

**Comment by cdlliuy** [comment]
Please check https://github.com/cloudfoundry-incubator/app-autoscaler/tree/develop/docs for details

**Comment by cdlliuy** [comment]
closed for no further update
