### ISSUE TITLE
Application is Scaling up but not Scaling down

### ISSUE THREAD

**Issue by ashwithahn** [cloudfoundry-incubator/app-autoscaler#369]
Hi Team,

I am unable to scale down the Instance, even if it has reached the minimum memory utilization.

Please find attached policy file 
[policy_file.txt](https://github.com/cloudfoundry-incubator/app-autoscaler/files/2240756/policy_file.txt)

Also current 
```
cf autoscaling-metrics bigapp2 memoryutil

Metrics Name            Instance Index          Value           At
memoryutil              0                       5%              2018-07-30T10:31:09Z
memoryutil              1                       3%              2018-07-30T10:31:23Z
memoryutil              2                       2%              2018-07-30T10:31:23Z
memoryutil              0                       5%              2018-07-30T10:31:24Z
memoryutil              3                       2%              2018-07-30T10:31:24Z
memoryutil              1                       3%              2018-07-30T10:31:38Z
memoryutil              2                       2%              2018-07-30T10:31:38Z
memoryutil              0                       5%              2018-07-30T10:31:39Z
memoryutil              3                       2%              2018-07-30T10:31:39Z
memoryutil              1                       3%              2018-07-30T10:31:53Z
memoryutil              2                       2%              2018-07-30T10:31:53Z
memoryutil              0                       5%              2018-07-30T10:31:54Z
memoryutil              3                       2%              2018-07-30T10:31:54Z

```
The Instance seems to be still in count of 3 and not Scaling down.

**Comment by cdlliuy** [comment]
@ashwithahn , according to your policy definition, the scale-in will happen when the average memory util is <= 2%.  
Looking at your instance metric below on 2018-07-30T10:31:38 ~ 2018-07-30T10:31:39. 
memoryutil              1                       3%              2018-07-30T10:31:38Z
memoryutil              2                       2%              2018-07-30T10:31:38Z
memoryutil              0                       5%              2018-07-30T10:31:39Z
memoryutil              3                       2%              2018-07-30T10:31:39Z
The avg memoryutil of the 4 instances are (3% + 2 % + 5% + 2% )/4 = 3% .  So, app-autoscaler won't trigger scale-in under this situation.

**Comment by ashwithahn** [comment]
@cdlliuy : Thank you very much :) This is resolved. I would like to close.
