### ISSUE TITLE
Couch and Postgres DBs

### ISSUE THREAD

**Issue by georgibarzev** [cloudfoundry-incubator/app-autoscaler#49]
Hi, 

Looking at the readme, both couch and postgres databases seem to be necessary to run the autoscaller. Could you elaborate on the need for/use of both of them? Is it a valid idea to use cf services?

Thanks

**Comment by fraenkel** [comment]
Couch is required for the initial version on master.
The current development is going to require Postgres which is on develop but non-functional.
