### ISSUE TITLE
ServiceBroker requires appId as request body for unbinding.

### ISSUE THREAD

**Issue by satoyan** [cloudfoundry-incubator/app-autoscaler#61]
ServiceBroker requires appId as request body for unbinding, but cf never passes such data.
It seems that I bound autosclaer service once, I will never unbind that.

**Comment by fraenkel** [comment]
The body must be {}.
See http://docs.cloudfoundry.org/services/api.html#unbinding

**Comment by satoyan** [comment]
I know that...

**Comment by satoyan** [comment]
https://github.com/cloudfoundry-incubator/app-autoscaler/blob/develop/servicebroker/lib/routes/binding.js#L105

**Comment by fraenkel** [comment]
Thank you for pointing that out. I have corrected the title.

**Comment by fraenkel** [comment]
Fixed with #64
