### ISSUE TITLE
Is develop branch available?

### ISSUE THREAD

**Issue by BongChan** [cloudfoundry-incubator/app-autoscaler#99]
I was trying to use 'develop branch' by using the guide(README.md), but it did not working.

I think develop branch's guide is not updated.

Is this develop branch available now??

**Comment by boyang9527** [comment]
'develop' branch is under active development to rewrite the components. 
If you want to have a try, please use 'couchdb' branch

**Comment by BongChan** [comment]
Thanks for quick reply.
When can I use 'developer' branch?
Because 'couchdb' brance does not seem to be any more development.

**Comment by fraenkel** [comment]
It will be a few more weeks to months. It is a bit hard to say. The master branch will contain a working version once we have something for people to consume.
The couchdb branch is not under any active development but does contain a working auto-scaler. However, there will be no way to migrate from the one to the new version.
